spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nambook
    username: postgres
    password: rnrdj123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
            show_sql: true


com:
  example:
    upload:
      path: C:\\Users\\SUN\\work\\springboot-react-nambook\\springApi\\upload


logging:
  level:
    org.springframework.security.web: trace